from datasets.pos import train_dataloader as pos_train_dataloader
from datasets.pos import test_dataloader as pos_test_dataloader
from datasets.sentiment import train_dataloader as sentiment_train_dataloader
from datasets.sentiment import test_dataloader as sentiment_test_dataloader